### ISSUE TITLE
Change User#active boolean to status enum

### ISSUE THREAD

**Issue by jdtornow** [jdtornow/challah#22]
Now that we're dropping pre 4.2 support, would be nice to use an enum in User instead of the older active flag.

Proposed states:

```ruby
class User < ActiveRecord::Base

  include Challah::Userable

  enum status: %w( active inactive )

end
```

This would keep the `active?` attribute as before, but use the new data type. This would be a breaking database change so it will need to provide an upgrade path or keep backward compatibility.

**Comment by jdtornow** [comment]
Any objections to this @philtr?

**Comment by philtr** [comment]
Nope! I like this idea.

**Comment by jdtornow** [comment]
Excellent, I'll get this in the next release too.
