### ISSUE TITLE
LoadError in SessionsController#new

### ISSUE THREAD

**Issue by atomkirk** [jdtornow/challah#25]
I literally did nothing more than create a brand new 4.2.6 Rails project, install the gem, run `rake challah:setup` and visit `localhost:3000/sign-in` and I got this:
![](http://d.pr/i/CBNi/id65fuQw+)

**Comment by jdtornow** [comment]
Hey @atomkirk -- Thanks for pointing this out. This looks to be an unforeseen issue from a change we made a while back to not require an `ApplicationController`. I just pushed a quick fix version 1.3.1. Let me know if that doesn't fix your problem.

**Comment by philtr** [comment]
@jdtornow @atomkirk I was able to reproduce this issue and can confirm that upgrading to v1.3.1 fixes it.

**Comment by jdtornow** [comment]
Excellent, thanks for checking @philtr!
