### ISSUE TITLE
Strip spaces?

### ISSUE THREAD

**Issue by philtr** [jdtornow/challah#30]
@jdtornow Would you be interested in a PR that stripped leading/trailing spaces from usernames/email addresses?

**Comment by jdtornow** [comment]
Hey @philtr that'd be great, if you're interested. 

I think this is [already happening on emails](https://github.com/jdtornow/challah/blob/master/lib/challah/concerns/user/attributeable.rb#L99-L101), but perhaps not on usernames? Worth another look for sure to keep things stored cleanly.

**Comment by philtr** [comment]
Hmm... I had an email address get saved that didn't get processed through that filter (it had capital letters and a space at the end). I guess I need to do some more digging to figure out what happened on my end here.

**Comment by philtr** [comment]
Haha, I just realized that the project in question is using a different auth library. 

![](http://www.reactiongifs.com/r/330f.gif)

**Comment by jdtornow** [comment]
Ha! No prob :)
