### ISSUE TITLE
Challah::Signup incompatible with ActionController::Parameters in Rails 5

### ISSUE THREAD

**Issue by philtr** [jdtornow/challah#31]
`Challah::Signup` [checks to see if the parameters passed in are a hash](https://github.com/jdtornow/challah/blob/master/lib/challah/signup.rb#L17). This check fails in Rails 5 (it might fail in Rails 4 as well, not sure) since the object is an `ActionController::Parameters` and not a hash.

I might be doing something wrong here ¯\\\_(ツ)_/¯. Story of my day so far!

**Comment by jdtornow** [comment]
Hey @philtr!

I'm not even sure that class is in use anymore within the rest of the code, if it is I can't find it. 

We could update the class to accept the params object in here, but I think the better way to do that would be within the controller (so by the time it gets into the `Signup` object everything is already in a hash.) 

Does something like this work in your controller where you're calling signup?

```ruby
signup  = Challah::Signup.new(params.permit!.to_h)
signup.save
```

**Comment by philtr** [comment]
Yeah, that's essentially what I did to fix it. I'm OK with that workaround if you want to keep it that way.

**Comment by jdtornow** [comment]
Great. I'm happy to add something in if you think it makes sense :)
